# Generated by Django 3.2.21 on 2023-09-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0002_auto_20230906_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rock',
            name='finished_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
