# Generated by Django 3.2.21 on 2023-09-14 11:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0003_alter_rock_finished_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rock',
            name='finished_image',
        ),
        migrations.RemoveField(
            model_name='rock',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='rock',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placholder', max_length=255, null=True, verbose_name='image'),
        ),
    ]
