# Generated by Django 3.2.21 on 2023-09-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0004_auto_20230914_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='rock',
            name='finished_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='rock',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='rock',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_i7zqny', null=True, upload_to='images/'),
        ),
    ]
