# Generated by Django 3.2.21 on 2023-09-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0005_auto_20230914_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rock',
            name='finished_image',
        ),
    ]
