# Generated by Django 3.2.21 on 2023-10-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0006_remove_rock_finished_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rock',
            options={'ordering': ['-date_found']},
        ),
        migrations.AddField(
            model_name='rock',
            name='finished_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
