# Generated by Django 3.2.21 on 2023-11-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0008_alter_rock_date_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='rock',
            name='rock_fossil',
            field=models.CharField(choices=[('rock', 'ROCK'), ('fossil', 'FOSSIL')], default='fossil', max_length=6),
        ),
    ]
