# Generated by Django 3.2.21 on 2023-11-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0010_rename_owner_rock_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rock',
            old_name='user',
            new_name='owner',
        ),
    ]
