# Generated by Django 3.2.21 on 2024-01-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0015_alter_rock_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rock',
            name='owner',
        ),
    ]
