# Generated by Django 3.2.21 on 2024-01-26 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rocks', '0017_rock_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rock',
            old_name='user',
            new_name='owner',
        ),
    ]
